### ISSUE TITLE
[Feature Request]  TOML config file

### ISSUE THREAD

**Issue by ahmubashshir** [yshui/picom#577]
### Platform
Manjaro 20.2

### Environment
XFCE 4.14

### picom version
vgit-dac85

### Feature Request
allow toml syntax in picom.conf.

Ex:
```toml
[wintypes.]
[wintypes.]
[wintypes.]
[wintypes.] = {
  tooltip = {
    fade = true,
    shadow = true,
    opacity = 0.75,
    focus = true,
    full-shadow = false
  },
  dock = { 
    shadow = false,
    opacity = 0.8
  },
  dnd = {
    shadow = false
  },
  popup_menu = {
    opacity = 0.8
  },
  dropdown_menu = {
    opacity = 0.8
  }
}
```
